workspace = { members = ["macros"] }
[package]
name = "dspsv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.vita]
title_id = "DSPSV0000"
title_name = "DSPSV"

[dependencies]
bilge = "0.2.0"
chrono = "0.4.31"
paste = "1.0.14"
rayon = "1.8.0"
static_assertions = "1.1.0"
once_cell = "1.19.0"
dspsv_macros = { path = "macros" }
sdl2 = "0.36.0"
libc = "0.2.150"

[target.armv7-sony-vita-newlibeabihf.dependencies]
vitasdk-sys = { version = "0.3.2", features = ["SceSysmem_stub",
    "SceAudioIn_stub",
    "SceAudio_stub",
    "SceCommonDialog_stub",
    "SceCtrl_stub",
    "SceDisplay_stub",
    "SceGxm_stub",
    "SceHid_stub",
    "SceMotion_stub",
    "SceTouch_stub"] }
