workspace = { members = ["macros"] }
[package]
name = "dspsv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.vita]
title_id = "DSPSV0000"
title_name = "DSPSV"
build_std = "std,panic_abort"

[dependencies]
bilge = { git = "https://github.com/Grarak/bilge.git" }
chrono = "0.4.33"
paste = "1.0.14"
static_assertions = "1.1.0"
dspsv_macros = { path = "macros" }

[target.armv7-unknown-linux-gnueabihf.dependencies]
libc = "0.2.153"
sdl2 = "0.36.0"

[target.armv7-sony-vita-newlibeabihf.dependencies]
vitasdk-sys = { version = "0.3.2", features = [
    "SceAppMgr_stub",
    "SceAudio_stub",
    "SceCommonDialog_stub",
    "SceCtrl_stub",
    "SceDisplay_stub",
    "SceGxm_stub",
    "SceKernelThreadMgr_stub",
    "SceLibKernel_stub",
    "SceSysmem_stub",
    "SceTouch_stub",
    "ScePgf_stub"
] }

[profile.release]
panic = "abort"
